# Gattino configuration file

# =============== Gemini =================
# https://ai.google.dev/gemini-api/docs/rate-limits
# =========================================
model: gemini/gemini-2.5-flash
#model: gemini/gemini-2.5-pro
#model: gemini/gemini-2.5-flash-lite
#model: gemini/gemini-2.0-flash
#model: gemini/gemini-2.0-flash-lite
#model: gemini/gemini-1.5-pro
#model: gemini/gemini-1.5-pro-latest
#model: gemini/gemini-1.5-pro-002
#model: gemini/gemini-1.5-flash
#model: gemini/gemini-1.5-flash-latest
#model: gemini/gemini-1.5-flash-002
#model: gemini/gemini-1.5-flash-8b
#model: gemini/gemini-1.5-flash-8b-latest
#model: gemini/gemini-2.0-flash-exp
#model: gemini/gemini-2.0-pro-exp
#model: gemini/gemini-2.0-flash-thinking-exp
#model: gemini/gemini-2.0-flash-thinking-exp-01-21
#model: gemini/learnlm-2.0-flash-experimental
#model: gemini/gemma-3-1b-it
#model: gemini/gemma-3-4b-it
#model: gemini/gemma-3-12b-it
#model: gemini/gemma-3-27b-it

# =============== OpenRouter ==============
# https://openrouter.ai/models/?q=free
# =========================================
#model: openrouter/google/gemini-2.0-flash-exp:free
#model: openrouter/deepseek/deepseek-chat-v3-0324:free
#model: openrouter/deepseek/deepseek-r1-0528:free
#model: openrouter/deepseek/deepseek-r1:free
#model: openrouter/moonshotai/kimi-k2:free
#model: openrouter/meta-llama/llama-3.3-70b-instruct:free
#model: openrouter/openai/gpt-oss-20b:free
#model: openrouter/agentica-org/deepcoder-14b-preview:free
#model: openrouter/arliai/qwq-32b-arliai-rpr-v1:free
#model: openrouter/cognitivecomputations/dolphin-mistral-24b-venice-edition:free
#model: openrouter/cognitivecomputations/dolphin3.0-mistral-24b:free
#model: openrouter/cognitivecomputations/dolphin3.0-r1-mistral-24b:free
#model: openrouter/deepseek/deepseek-r1-0528-qwen3-8b:free
#model: openrouter/deepseek/deepseek-r1-distill-llama-70b:free
#model: openrouter/deepseek/deepseek-r1-distill-qwen-14b:free
#model: openrouter/featherless/qwerky-72b:free
#model: openrouter/google/gemini-2.5-pro-exp-03-25
#model: openrouter/google/gemma-2-9b-it:free
#model: openrouter/google/gemma-3-12b-it:free
#model: openrouter/google/gemma-3-27b-it:free
#model: openrouter/google/gemma-3-4b-it:free
#model: openrouter/google/gemma-3n-e2b-it:free
#model: openrouter/google/gemma-3n-e4b-it:free
#model: openrouter/meta-llama/llama-3.1-405b-instruct:free
#model: openrouter/meta-llama/llama-3.2-11b-vision-instruct:free
#model: openrouter/meta-llama/llama-3.2-3b-instruct:free
#model: openrouter/microsoft/mai-ds-r1:free
#model: openrouter/mistralai/devstral-small-2505:free
#model: openrouter/mistralai/mistral-7b-instruct:free
#model: openrouter/mistralai/mistral-nemo:free
#model: openrouter/mistralai/mistral-small-24b-instruct-2501:free
#model: openrouter/mistralai/mistral-small-3.1-24b-instruct:free
#model: openrouter/mistralai/mistral-small-3.2-24b-instruct:free
#model: openrouter/moonshotai/kimi-dev-72b:free
#model: openrouter/moonshotai/kimi-vl-a3b-thinking:free
#model: openrouter/nousresearch/deephermes-3-llama-3-8b-preview:free
#model: openrouter/nvidia/llama-3.1-nemotron-ultra-253b-v1:free
#model: openrouter/qwen/qwen-2.5-72b-instruct:free
#model: openrouter/qwen/qwen-2.5-coder-32b-instruct:free
#model: openrouter/qwen/qwen2.5-vl-32b-instruct:free
#model: openrouter/qwen/qwen2.5-vl-72b-instruct:free
#model: openrouter/qwen/qwen3-14b:free
#model: openrouter/qwen/qwen3-235b-a22b:free
#model: openrouter/qwen/qwen3-30b-a3b:free
#model: openrouter/qwen/qwen3-4b:free
#model: openrouter/qwen/qwen3-8b:free
#model: openrouter/qwen/qwen3-coder:free
#model: openrouter/qwen/qwq-32b:free
#model: openrouter/rekaai/reka-flash-3:free
#model: openrouter/sarvamai/sarvam-m:free
#model: openrouter/shisa-ai/shisa-v2-llama3.3-70b:free
#model: openrouter/tencent/hunyuan-a13b-instruct:free
#model: openrouter/tngtech/deepseek-r1t-chimera:free
#model: openrouter/tngtech/deepseek-r1t2-chimera:free
#model: openrouter/z-ai/glm-4.5-air:free
# =============== GROQ ====================
# https://console.groq.com/docs/rate-limits
# =========================================
#model: groq/qwen3-32b
#model: groq/moonshotai/kimi-k2-instruct
#model: groq/allam-2-7b
#model: groq/compound-beta
#model: groq/compound-beta-mini
#model: groq/deepseek-r1-distill-llama-70b
#model: groq/distil-whisper-large-v3-en
#model: groq/gemma2-9b-it
#model: groq/llama-3.1-8b-instant
#model: groq/llama-3.3-70b-versatile
#model: groq/llama3-70b-8192
#model: groq/llama3-8b-8192
#model: groq/meta-llama/llama-4-maverick-17b-128e-instruct
#model: groq/meta-llama/llama-4-scout-17b-16e-instruct
#model: groq/meta-llama/llama-guard-4-12b
#model: groq/meta-llama/llama-prompt-guard-2-22m
#model: groq/meta-llama/llama-prompt-guard-2-86m
#model: groq/openai/gpt-oss-120b
#model: groq/openai/gpt-oss-20b
#model: groq/playai-tts
#model: groq/playai-tts-arabic
#model: groq/whisper-large-v3
#model: groq/whisper-large-v3-turbo

# =============== Together AI =============
# https://docs.together.ai/docs/rate-limits 
# =========================================
#model: together/meta-llama/Llama-3.3-70B-Instruct-Turbo-Free
#model: together/meta-llama/Llama-Vision-Free
#model: together/deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free
#model: together/black-forest-labs/FLUX.1-schnell-Free
#model: together/meta-llama/Llama-3.3-70B-Instruct-Turbo
#model: together/meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo
#model: together/deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
#model: together/moonshotai/Kimi-K2-Instruct
#model: together/mistralai/Mistral-7B-Instruct-v0.3
#model: together/Qwen/Qwen2.5-7B-Instruct-Turbo
#model: together/meta-llama/Llama-3.2-3B-Instruct-Turbo
#model: together/google/gemma-3n-E4B-it
#model: together/openai/gpt-oss-120b

# =============== Z.AI ====================
# https://open.bigmodel.cn/
# =========================================
#model: z-ai/glm-4.5-flash
#model: z-ai/glm-4.5
#model: z-ai/glm-4.5-air

# Path to ollama binary (legacy - not used with remote APIs)
ollama_path: /usr/local/bin/ollama
