general {
    lock_cmd = sudo -n systemctl restart fprintd; pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl eval 'hl.dispatch(hl.dsp.dpms({ action = "on" }))'  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 1500                                # 25min.
    on-timeout = brightnessctl -s set 40         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r                 # monitor backlight restore.
}


# send notification before locking the screen
listener {
    timeout = 3595                                # 5s before locking
    on-timeout = notify-send "Screen Lock" "Locking the screen after 5 seconds."
}

# locking the screen
listener {
    timeout = 3600                                # 1h
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

listener {
    timeout = 3660                                # 1h1min
    on-timeout = hyprctl eval 'hl.dispatch(hl.dsp.dpms({ action = "off" }))'        # screen off when timeout has passed
    on-resume = hyprctl eval 'hl.dispatch(hl.dsp.dpms({ action = "on" }))'          # screen on when activity has been detected after timeout.
}

