set shell := ["bash", "-euo", "pipefail", "-c"]

default:
    @just --list

typecheck:
    ags types 'Astal*' --ignore Gtk3 --ignore Astal3 --update
    tsc --noEmit --skipLibCheck -p tsconfig.json

test:
    just typecheck

run:
    ags quit || true
    ags run .
