# Base16 Atelier Sulphurpool - Ranger Colorscheme
# Bram de Haan (http://atelierbramdehaan.nl)
# Generated by tinty

from ranger.gui.colorscheme import ColorScheme
from ranger.gui.color import *

class base16(ColorScheme):
    progress_bar_color = 8

    def use(self, context):
        fg, bg, attr = default_colors

        if context.reset:
            return default_colors

        elif context.in_browser:
            if context.selected:
                attr = reverse
            else:
                attr = normal
            if context.empty or context.error:
                fg = 1  # red
                bg = 0
            if context.border:
                fg = 8  # gray
            if context.image:
                fg = 3  # yellow
            if context.video:
                fg = 5  # magenta
            if context.audio:
                fg = 6  # cyan
            if context.document:
                fg = 7  # white
            if context.container:
                attr |= bold
                fg = 9  # bright red
            if context.directory:
                attr |= bold
                fg = 4  # blue
            elif context.executable and not \
                    any((context.media, context.container,
                       context.fifo, context.socket)):
                attr |= bold
                fg = 2  # green
            else:
                # Regular files should be clearly visible
                fg = default
            if context.socket:
                fg = 5  # magenta
                attr |= bold
            if context.fifo or context.device:
                fg = 3  # yellow
                if context.device:
                    attr |= bold
            if context.link:
                fg = 6 if context.good else 1  # cyan or red
            if context.bad:
                bg = 1  # red
            if context.tag_marker and not context.selected:
                attr |= bold
                if fg in (1, 5):
                    fg = 0  # black
                else:
                    fg = 1  # red
            if not context.selected and (context.cut or context.copied):
                fg = 8  # gray
                bg = 0
            if context.main_column:
                if context.selected:
                    attr |= bold
                if context.marked:
                    attr |= bold
                    fg = 3  # yellow
            if context.badinfo:
                if attr & reverse:
                    bg = 1  # red
                else:
                    fg = 1  # red

        elif context.in_titlebar:
            attr |= bold
            if context.hostname:
                fg = 1 if context.bad else 2  # red or green
            elif context.directory:
                fg = 4  # blue
            elif context.tab:
                if context.good:
                    bg = 2  # green
            elif context.link:
                fg = 6  # cyan

        elif context.in_statusbar:
            if context.permissions:
                if context.good:
                    fg = 6  # cyan
                elif context.bad:
                    fg = 1  # red
            if context.marked:
                attr |= bold | reverse
                fg = 3  # yellow
            if context.message:
                if context.bad:
                    attr |= bold
                    fg = 1  # red
            if context.loaded:
                bg = self.progress_bar_color
            if context.vcsinfo:
                fg = 4  # blue
                attr &= ~bold
            if context.vcscommit:
                fg = 2  # green
                attr &= ~bold

        if context.text:
            if context.highlight:
                attr |= reverse

        if context.in_taskview:
            if context.title:
                fg = 4  # blue

            if context.selected:
                attr |= reverse

            if context.loaded:
                if context.selected:
                    fg = self.progress_bar_color
                else:
                    bg = self.progress_bar_color

        if context.vcsfile and not context.selected:
            attr &= ~bold
            if context.vcsconflict:
                fg = 1  # red
            elif context.vcschanged:
                fg = 9  # bright red
            elif context.vcsunknown:
                fg = 1  # red
            elif context.vcsstaged:
                fg = 2  # green
            elif context.vcssync:
                fg = 6  # cyan
            elif context.vcsignored:
                fg = default

        elif context.vcsremote and not context.selected:
            attr &= ~bold
            if context.vcssync:
                fg = 6  # cyan
            elif context.vcsbehind:
                fg = 1  # red
            elif context.vcsahead:
                fg = 4  # blue
            elif context.vcsdiverged:
                fg = 1  # red
            elif context.vcsunknown:
                fg = 1  # red

        return fg, bg, attr