set shell := ["bash", "-euo", "pipefail", "-c"]

default:
    @just --list

test:
    just --justfile ../justfile --working-directory .. _test-control-panel

test-ci:
    just --justfile ../justfile --working-directory .. _test-ci-control-panel

run:
    ags quit || true
    ags run .
