# Base16 Atelier Sulphurpool - ZSH Theme Colors
# Scheme by Bram de Haan (http://atelierbramdehaan.nl)
# Generated by tinty

# Base16 colors for use in shell scripts and prompts
export BASE16_THEME="atelier-sulphurpool"
export BASE16_SCHEME="Atelier Sulphurpool"

# Base colors
export BASE00="202746"  # Default Background
export BASE01="293256"  # Lighter Background
export BASE02="5e6687"  # Selection Background
export BASE03="6b7394"  # Comments, Invisibles
export BASE04="898ea4"  # Dark Foreground
export BASE05="979db4"  # Default Foreground
export BASE06="dfe2f1"  # Light Foreground
export BASE07="f5f7ff"  # Light Background
export BASE08="c94922"  # Variables, Tags, Markup Link Text
export BASE09="c76b29"  # Integers, Boolean, Constants
export BASE0A="c08b30"  # Classes, Markup Bold, Search Text BG
export BASE0B="ac9739"  # Strings, Inherited Class, Markup Code
export BASE0C="22a2c9"  # Support, Regular Expressions, Escape Characters
export BASE0D="3d8fd1"  # Functions, Methods, Attribute IDs, Headings
export BASE0E="6679cc"  # Keywords, Storage, Selector, Markup Italic
export BASE0F="9c637a"  # Deprecated, Opening/Closing Embedded Language Tags

# FZF colors (for your fzf integration)
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --color=bg+:#$BASE01,bg:#$BASE00,spinner:#$BASE0C,hl:#$BASE0D --color=fg:#$BASE04,header:#$BASE0D,info:#$BASE0A,pointer:#$BASE0C --color=marker:#$BASE0C,fg+:#$BASE06,prompt:#$BASE0A,hl+:#$BASE0D"